### ISSUE TITLE
拼音搜索仍无效

### ISSUE THREAD

**Issue by CialloAlone** [Chaoses-Ib/IbEverythingExt#1]
x64位安装版V1.4.1.1009 (x64) ，已安装VC_redist.x64.exe ，并将version.dll放入C:\Program Files\Everything ，拼音搜索仍旧无效

**Comment by Chaoses-Ib** [comment]
应该是 Windows 10 的原因，Everything 在 Windows 10 下不会加载 version.dll，develop 分支已经修复了。

**Comment by Chaoses-Ib** [comment]
之前没有在实机测试，刚才测试了下发现总文件在百万以上的话查询会很慢，需要几秒钟才能得到结果，我准备再删减些不常用汉字，之后再更新 v0.2。

**Comment by Chaoses-Ib** [comment]
[v0.2](https://github.com/Chaoses-Ib/IbEverythingExt/releases/tag/v0.2) 已更新。
