### ISSUE TITLE
支持调用 Everything 进行查询的第三方程序

### ISSUE THREAD

**Issue by Chaoses-Ib** [Chaoses-Ib/IbEverythingExt#10]
出于兼容性与性能考虑，只对以下程序启用了处理：

* [stnkl/EverythingToolbar](https://github.com/stnkl/EverythingToolbar)
  [Any possibility to support IbEverythingExt? · Issue #205 · stnkl/EverythingToolbar](https://github.com/stnkl/EverythingToolbar/issues/205)
* [uTools](https://u.tools) 本地搜索
  [everything添加拼音搜索的插件,utool中没有生效 - 猿料](https://yuanliao.info/d/4207-everythingutool)

如果有其它程序需要支持，请在此上报。

**Comment by WankkoRee** [comment]
+1

[utools](https://u.tools/)的`本地搜索`插件作为第三方调用同样也没有生效。

![image](https://user-images.githubusercontent.com/21287731/134235548-86ca0e07-3a1a-47ab-ba45-36d6409d707e.png)

![image](https://user-images.githubusercontent.com/21287731/134235636-9429de2f-acfc-42c1-a6de-3100e35d02a4.png)

**Comment by Chaoses-Ib** [comment]
> +1
> 
> [utools](https://u.tools/)的`本地搜索`插件作为第三方调用同样也没有生效。

这个 issue 是新功能建议，不是 bug 反馈，第三方调用支持还没有实现。

**Comment by 72706057** [comment]
火柴
https://www.huochaipro.com/

**Comment by fhwid** [comment]
Flow-Launcher，这个工具也是开源的，安装everything插件后，没办法用拼音首字母搜索，能否适配下，谢谢

**Comment by Chaoses-Ib** [comment]
* [Flow Launcher](https://github.com/Flow-Launcher/Flow.Launcher) 的 [Everything 插件](https://github.com/Flow-Launcher/Flow.Launcher.Plugin.Everything)
* [火柴（火萤酱）](https://www.huochaipro.com/)本地搜索
* [Wox](https://github.com/Wox-launcher/Wox) 的 Everything 插件

**Comment by Chaoses-Ib** [comment]
Edit 模式停止维护，PCRE 模式性能和兼容性达标，不再限制第三方调用程序。
