### ISSUE TITLE
支持 Everything Lite

### ISSUE THREAD

**Issue by Marukon** [Chaoses-Ib/IbEverythingExt#11]
版本 V1.4.1.1009 Lite (x64) ，放入dll并且安装运行库，仍然无效，请求作者适配，谢谢。

**Comment by ashuang001** [comment]
我也是.

**Comment by Marukon** [comment]
> Lite 版[不允许 IPC](https://www.voidtools.com/zh-cn/support/everything/installing_everything/)，没法动态构建汉字集，拼音搜索性能会很差，而且还需要维护两份代码，目前不会支持。
> 有什么必须用 Lite 版而不用安装版或者便携版的原因吗？

感谢作者大大回复，已经用回普通版。
