### ISSUE TITLE
能否基于everything 做个共享网盘

### ISSUE THREAD

**Issue by musaart** [Chaoses-Ib/IbEverythingExt#16]
能否基于everything 做个局域网共享网盘

**Comment by Chaoses-Ib** [comment]
Everything 不是有 HTTP 和 ETP 服务器功能吗？

**Comment by musaart** [comment]
无法做权限管控




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月27日(星期一) 下午2:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chaoses-Ib/IbEverythingExt] 能否基于everything 做个共享网盘 (#16)





 
Everything 不是有 HTTP 和 ETP 服务器功能吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Chaoses-Ib** [comment]
可以考虑使用 v1.5 Alpha 的 [Everything Server](http://www.voidtools.com/forum/viewtopic.php?f=12&t=9794) 功能，支持添加多个用户，可以为每个用户设置访问范围。
