### ISSUE TITLE
罕见拼音问题

### ISSUE THREAD

**Issue by feadsf** [Chaoses-Ib/IbEverythingExt#20]
![aaa](https://user-images.githubusercontent.com/26196835/135544788-b778b651-bf56-437c-b928-bceafafe0f72.png)

图上最后二行的文字中, 拼音首字母着重显示不对, "款"字的首字母应该是"k".

**Comment by feadsf** [comment]
![snap019](https://user-images.githubusercontent.com/26196835/135556885-b86e0308-246f-421b-b205-a8b3e26512f4.png)

上图中第一行和第三行中的粗体字也与拼音首字母不匹配.

**Comment by Chaoses-Ib** [comment]
[“款”](https://zh.wiktionary.org/wiki/%E6%AC%BE)在维基词典上有 xīn 的音，不过没找到用例。
[“渠”](https://www.zdic.net/hans/%E6%B8%A0)有 jù 的音，如“掾部渠有其人乎”。
[“解”](https://www.zdic.net/hant/%E8%A7%A3)当姓氏时的音是 xiè。

前两个音的确很不常用，但是删除不常用音会有很多问题，比如到底什么样的音才不常用？一万人里有一个人用到了该保留吗？就算能讨论出一个使用频率的标准，目前也没有拼音频率数据库可以使用，而人工处理几万汉字成本又太高。
除了删除，分词也是一种办法，但是分词的准确性又无法保证，比如“解元.txt”，除了机主本人之外，谁都没法确定这到底是[科举的“jiè 元”](https://zh.wikipedia.org/wiki/%E8%A7%A3%E5%85%83)，还是[人名“xiè 元”](https://baike.baidu.com/item/%E8%A7%A3%E5%85%83/3699718#viewPageContent)。

**Comment by Chaoses-Ib** [comment]
如果想要同时保留完整性和便利性，根据读音的使用频率为搜索结果赋权重是一种办法，但一是没有数据库，二是也很难让 Everything 按权重显示结果。
在不能同时满足的情况下，我倾向于优先保证完整性，毕竟搜多了只是有些碍眼，搜少了就只能删掉搜索，自己输入汉字了。

**Comment by feadsf** [comment]
“款”和“渠”是多音字, 这我确实不知道, 孤陋寡闻了. 我赞成完整性优先的设计, 搜索时不遗漏是必须保证的.
一直想找一个 everything 上的首字母搜索利器, 终于找到了, 谢谢你的作品.

**Comment by feadsf** [comment]
“款”和“渠”是多音字, 这我确实不知道, 原谅我孤陋寡闻了. 我赞成完整性优先的设计, 搜索时不遗漏是必须保证的.
一直想找一个 everything 上的首字母搜索利器, 终于找到了, 谢谢你的作品.

**Comment by Chaoses-Ib** [comment]
目前正在考虑移除包含罕见音较多的数据源，或者只保留均为常见音的数据源。

**Comment by feadsf** [comment]
或许可以设计一个选项或开关, 进行完整的搜索(包含罕见音)或常用的搜索(去除罕见音)?

**Comment by Chaoses-Ib** [comment]
我的想法也是加一个配置开关，默认关闭，有需要的人自己开启。
