### ISSUE TITLE
匹配错误

### ISSUE THREAD

**Issue by StrollStars** [Chaoses-Ib/IbEverythingExt#21]
如图，匹配的内容中有拼音首字母不相符的
![2021-10-01_210631](https://user-images.githubusercontent.com/10942225/135627209-90de3f70-228c-4003-8255-9ba132137a5a.jpg)
下面那个能理解，是多音字。

**Comment by Chaoses-Ib** [comment]
[“圣”](https://www.zdic.net/hant/%E5%9C%A3)有 kū 的音，如“吾负母而逃，圣野菜充饥”。

关于罕见音的问题，请到 #20 讨论。
