### ISSUE TITLE
版本 V1.5.0.1279a (x64) + 0.4 版本，开启快速选择，左侧键值不能和右侧列表水平对应。

### ISSUE THREAD

**Issue by SiaYung** [Chaoses-Ib/IbEverythingExt#31]
如题吧。
图片：https://i.loli.net/2021/10/12/8OIcxGdZnsJrHuX.png
![image](https://user-images.githubusercontent.com/50246090/136935251-703c2804-89e1-400e-9b9a-bbecf5b54146.png)

**Comment by Chaoses-Ib** [comment]
因为 Everything 的列表是自绘的，没法很好的插入列（feat-quick-select-header 分支），快速选择是新加了一个列表框，独立于 Everything 的列表存在。
v1.5a 的 header 变高了几个像素，不过偏差这么大应该是 DPI 或者 Zoom 的问题，在 v1.4 下也存在。之后的版本会尝试同步 header 高度、列表行高、字体和背景色。

**Comment by Chaoses-Ib** [comment]
![image](https://user-images.githubusercontent.com/50246090/153294630-78e93558-e93a-49fe-8aa1-eb50ec95a3da.png)
v1.5a 下已修复，会在扩展 v0.5 正式版中发布。
