### ISSUE TITLE
输入搜索并切换窗口，everything输入框出现乱码

### ISSUE THREAD

**Issue by brucmao** [Chaoses-Ib/IbEverythingExt#33]
步骤
1.everything输入框随便输入 ， 如  arch

2.切换everything窗口，让everythingying 最小化到托盘，我用如下快捷键

![Snipaste_2021-11-04_10-05-22](https://user-images.githubusercontent.com/6119652/140245295-d48b161b-fe01-4716-a16f-3899a81b7350.png)
3.再次用快捷键切换everything到前台

![Snipaste_2021-11-04_10-06-50](https://user-images.githubusercontent.com/6119652/140245435-5d1d7ac3-552e-4bde-a3aa-2fc29d5dde05.png)

bug出现了，输入框出现一些乱码输入

everything版本 V1.5.0.1279a (x64)
win10专业版 19043.1288

**Comment by Chaoses-Ib** [comment]
v0.5 会停止维护现在的 Edit 模式，添加 PCRE 模式，不会有这个 bug。
