### ISSUE TITLE
Error with Everything-1.5.0.1284a.x64

### ISSUE THREAD

**Issue by ahlarry** [Chaoses-Ib/IbEverythingExt#35]
Microsoft Visual C++ Runtime Library
Runtime Error!
Program:E:\Tools\Everything64.exe
This application has requested the Runtime to terminate it in an unusualway.
Please contact the application's support team for more information.
确定

**Comment by ahlarry** [comment]
0.5 α

**Comment by Chaoses-Ib** [comment]
PCRE 模式目前只支持 Everything v1.4.1.1009（[README](https://github.com/Chaoses-Ib/IbEverythingExt/tree/v0.5-alpha)），v1.5a 会在 v0.5 正式发布前支持，不过也只会支持最新的 v1.5a 版本。没有回落到 Edit 模式而是直接引起报错确实是个 bug，可能是版本判断出了问题。
