### ISSUE TITLE
Fluent Search适配

### ISSUE THREAD

**Issue by fanhwid** [Chaoses-Ib/IbEverythingExt#39]
![image](https://user-images.githubusercontent.com/72638192/146144245-22b3fe25-d8e6-4a2c-aec0-2f2ecf355486.png)
在fluent search里面，设置使用everything索引的时候，不支持使用拼音首字母，请大神考虑下适配，🙇‍

**Comment by Chaoses-Ib** [comment]
[v0.5-alpha](https://github.com/Chaoses-Ib/IbEverythingExt/releases/tag/v0.5-alpha) 已经不限制程序了，支持简拼和全拼搜索，不过目前只支持 Everything v1.4.1.1009 x64 安装版/便携版。

**Comment by fanhwid** [comment]
problem solved,tks
