### ISSUE TITLE
搜索历史功能破坏

### ISSUE THREAD

**Issue by Youxikong** [Chaoses-Ib/IbEverythingExt#4]
下拉历史和历史菜单，点击历史搜索记录都无效。

**Comment by scavin** [comment]
重现+1，开启之前的历史记录还在。

**Comment by Chaoses-Ib** [comment]
剩余问题：
* 进程生命期内的搜索
  * 在下拉列表中重复显示；
  * 在搜索历史菜单中显示错误；
  * 在搜索历史管理器中显示错误。

**Comment by Chaoses-Ib** [comment]
Edit 模式停止维护，PCRE 模式无该问题。
