### ISSUE TITLE
更新到Everything-1.4.1.1015.x64后出错

### ISSUE THREAD

**Issue by feadsf** [Chaoses-Ib/IbEverythingExt#41]
更新到Everything-1.4.1.1015.x64后, 启动Everything出错. 将本插件文件 WindowsCodecs.dll 删除后, 启动Everything正常.

**Comment by Chaoses-Ib** [comment]
扩展版本是 v0.4 还是 v0.5-alpha？

**Comment by Chaoses-Ib** [comment]
如果是 v0.5-alpha 的话就是版本识别的问题，与 #35 是同一个原因，v0.5-alpha 目前只支持 v1.4.1.1009，可以先回滚回去：
v1.4.1.1009 x64 [安装版](https://www.voidtools.com/Everything-1.4.1.1009.x64-Setup.exe)/[便携版](https://www.voidtools.com/Everything-1.4.1.1009.x64.zip)
