### ISSUE TITLE
[bug]左侧序号提示显示有些偏移

### ISSUE THREAD

**Issue by godefy** [Chaoses-Ib/IbEverythingExt#48]
![image](https://user-images.githubusercontent.com/19462833/162852645-778ed532-0a36-424e-98b9-5c5f67257078.png)
基本上从字母开始，就偏移得没法正常使用了。这个看能否一下，如果能直接在原有的ev界面上生成这些序号提示就最好了，这样背景色不一致的问题也能解决了。

**Comment by Chaoses-Ib** [comment]
在 Everything 1.5a 下有问题吗？键列表在 1.4 下不支持 Ctrl 缩放，缩放后会导致错位。

键列表最初的实现就是直接插入列的，即 [feat-quick-select-header 分支](https://github.com/Chaoses-Ib/IbEverythingExt/tree/feat-quick-select-header)，但是因为 Everything 的高度自绘，有非常多很严重的 bug，迫不得已才用了外置列表。

**Comment by godefy** [comment]
我这个截图就是在将缩放设为默认(快捷键ctrl+0)后截的。
1.5还没有试，我晚点试试看吧，1.5我刚发现，还没来得及同步配置，一时半会儿还没法用呢。

**Comment by godefy** [comment]
试了下，1.5里如果不缩放的话，是正常的。
