### ISSUE TITLE
请问现在1.5版有最新的lng汉化文件吗?

### ISSUE THREAD

**Issue by godefy** [Chaoses-Ib/IbEverythingExt#49]
昨天突然发现everything居然很低调的出了1.5版(官网一直没发布，是在这个插件的介绍里看到有说，然后搜关键字搜到了他们论坛)
但网上找了下，对应的汉化文件居然一直没有更新。用1.4的汉化文件，很多内容都还是英文的。
不知道有没有1.5版对应的汉化文件。

**Comment by Chaoses-Ib** [comment]
我不知道，你可以联系下 Everything 的汉化人员问问看。

**Comment by godefy** [comment]
好的
