### ISSUE TITLE
不支持Everything 1.5 Alpha版本

### ISSUE THREAD

**Issue by 775405984** [Chaoses-Ib/IbEverythingExt#5]
http://www.voidtools.com/forum/viewtopic.php?f=12&t=9787

**Comment by Chaoses-Ib** [comment]
由于 1.5 的 IPC SDK 尚未公开，目前无法适配，请按照 [Everything 的官方说明](http://www.voidtools.com/forum/viewtopic.php?f=12&t=9799#isntance) 禁用新版 IPC 接口（在 `Everything-1.5a.ini` 的末尾添加 `alpha_instance=0`）。

![image](https://user-images.githubusercontent.com/50246090/134386563-93227449-806d-4d73-956c-a3d1bcec9922.png)

**Comment by Chaoses-Ib** [comment]
v1.5 的 IPC 接口并没有改变，只是 Alpha 版默认启用了命名实例，目前已经添加了支持，不再需要配置。不过如果需要从第三方程序调用的话，仍需要进行配置（官方 IPC SDK 不支持命名实例）。

**Comment by ahlarry** [comment]
> v1.5 的 IPC 接口并没有改变，只是 Alpha 版默认启用了命名实例，目前已经添加了支持，不再需要配置。不过如果需要从第三方程序调用的话，仍需要通过配置关闭命名实例（官方 IPC SDK 不支持命名实例）。

1278a 配0.3，默认不改配置仍然不可用

**Comment by Chaoses-Ib** [comment]
”目前“指的是 develop 分支，发布 v0.4 时会并入。
