### ISSUE TITLE
[bug]使用这个插件以后，会强制打开文件或目录时关闭everything

### ISSUE THREAD

**Issue by godefy** [Chaoses-Ib/IbEverythingExt#51]
本来这个逻辑是通过everything里的设置项实现的
![image](https://user-images.githubusercontent.com/19462833/162867865-16acf53e-ddc0-45cd-8400-432f12f42492.png)
，但用了这个插件，这个设置项就失效了，变成了固定的打开就会关闭everything窗口。
希望能修复一下，不要强制覆盖原有的可配置项。

**Comment by Chaoses-Ib** [comment]
临时解决方案：设置配置文件中的 `close_everything` 为 `false`。

**Comment by godefy** [comment]
好的。
正常来说，插件配置里这部分只决定插件提供的热键调用去打开时候的处理规则。目前相当于扩散到了软件全局设置。

**Comment by Chaoses-Ib** [comment]
你确定会扩散到全局吗？只有 Alt 热键和单字母键才可能触发快速选择，直接按 Enter 或者 Ctrl+Enter 是不经任何处理的。

**Comment by godefy** [comment]
我好像没有试enter和ctrl+enter，我试的是鼠标双击文件 或 路径，这两个操作会受影响。

**Comment by Chaoses-Ib** [comment]
这两个操作我在 v1.4.1.1015 和 v1.5.0.1305 下都无法复现问题，况且扩展也根本没有处理任何鼠标消息，这两个操作的行为只受 Everything 自身控制，是不是你看错配置了？

**Comment by godefy** [comment]
等下我重新复现试试哈

**Comment by godefy** [comment]
1.5里试了下，是正常的。没有这个问题了。

**Comment by godefy** [comment]
1.4刚才也试了下，还是没复现出来。可能之前是我自己试的时候的一些问题😅。
