### ISSUE TITLE
请问一下1.5a版本的相关内容

### ISSUE THREAD

**Issue by godefy** [Chaoses-Ib/IbEverythingExt#52]
想问下，1.5a版本提升大吗? 是否稳定?
因为我看1.5a和1.4的配置不太一样，升级的话需要手动去同步配置有点麻烦。在考虑要不要升级呢。

顺带再问下怎么给这里的帖子加的标签?是版块所有者才能加，还是所有人都能加?
![image](https://user-images.githubusercontent.com/19462833/163287526-a6b0c16a-e3e7-45c9-b345-0e83d5cfda81.png)

**Comment by Chaoses-Ib** [comment]
功能和性能都有不少增强，稳定性方面至少我还没有遇到过 bug。

配置可以从 1.4 导出后再导入到 1.5a（过滤器和书签要单独导出）。

标签只有仓库的 collaborator 才能添加。

**Comment by godefy** [comment]
我没有找到导出配置的按钮，是指直接将1.4的ini配置覆盖1.5的ini配置吗?

**Comment by Chaoses-Ib** [comment]
是我记错了，1.4 只能导出过滤器、书签和搜索历史，1.5a 才能导出设置。你可以试试直接用 1.5a 导入 1.4 的配置文件，在 Tools 菜单里。

**Comment by godefy** [comment]
谢谢，刚才已经成功将配置导入到1.5了。
也顺带把这个插件加进去了，接过发现插件不支持那个版本🤣
![image](https://user-images.githubusercontent.com/19462833/163397217-4e3764e8-f3fa-4fa1-a506-d1ef2887f71e.png)
能给支持一下最新版吗：版本 V1.5.0.1309a (x64)

**Comment by Chaoses-Ib** [comment]
目前有点忙，你需要的话可以先退到 1305 [安装版](https://www.voidtools.com/Everything-1.5.0.1305a.x64-Setup.exe)/[便携版](https://www.voidtools.com/Everything-1.5.0.1305a.x64.zip)。

**Comment by godefy** [comment]
好的，不着急，有空再弄吧。我刚按说明里给回退到1296了，1305能用那更好了。

**Comment by godefy** [comment]
额 刚下了你发这个1305a，也是报那个错，是不是最高只支持到了1296啊?

**Comment by Chaoses-Ib** [comment]
你用的是扩展的 v0.6-alpha？1305 是 v0.6-alpha.2 支持的，[Releases](https://github.com/Chaoses-Ib/IbEverythingExt/releases) 里有写。我现在用的就是 1305。

**Comment by godefy** [comment]
额 看了下是0.5的，不知道之前为啥下成了0.5。刚才下了个0.6的就可以啦，感谢🤓~

**Comment by Chaoses-Ib** [comment]
那个应该不是 0.5，是 0.6-alpha，0.5 还没加上面那个错误提示，alpha 版我一般不改版本号。

**Comment by godefy** [comment]
明白啦，我刚才看了一眼刚下这个0.6版，上面也是显示的0.5。
