### ISSUE TITLE
模式选择问题

### ISSUE THREAD

**Issue by StrollStars** [Chaoses-Ib/IbEverythingExt#55]
Edit 模式存在不支持正则表达式的问题，同时也已经停止维护。
而配置文件默认设置“优先尝试 PCRE 模式，PCRE 模式不可用时使用 Edit 模式”。

①请问PCRE 模式是什么？搜了下和PHP有关，但没能看懂。
②为什么PCRE 模式会不可用，如何让其可用？

**Comment by Chaoses-Ib** [comment]
1. PCRE 是一个正则表达式引擎，Everything 使用它来匹配正则表达式，PHP 也是。扩展的 PCRE 模式是指强制 Everything 开启正则模式，劫持其内置的 PCRE 引擎，从而实现使用自己的匹配引擎进行拼音匹配。
2. 每个版本的 Everything 中的 PCRE 引擎的函数地址都会改变，因为目前没有实现特征码匹配，因此需要手动为每个 Everything 版本指定函数地址。如果你用了不在支持列表中的 Everything 版本，PCRE 模式就会不可用，反之则会可用。在 [v0.6-alpha 及以上版本](https://github.com/Chaoses-Ib/IbEverythingExt/releases)，默认的行为已更改为只使用 PCRE 模式，如果不可用则会弹窗提示，同时停用拼音搜索。

总之，只要你使用主页里列出的 Everything 版本，就会直接使用 PCRE 模式。Edit 模式存在着[至少六个 bug 和严重的性能问题](https://github.com/Chaoses-Ib/IbEverythingExt/blob/develop/docs/pinyin_search/edit_mode.md)，没有使用价值，不需要考虑。

**Comment by StrollStars** [comment]
也就是说从0.6版本开始，PCRE为默认模式。如果可用，则同步强制开启正则模式；如果不可用，则拼音搜索就不能用了。
这么理解对吗？

**Comment by Chaoses-Ib** [comment]
对。不过强制开启正则对用户是透明的，如果用户手动开启了正则就会照常进行正则匹配，只有在没开启时才会进行拼音匹配，不影响使用正则。

**Comment by StrollStars** [comment]
@Chaoses-Ib 但是在启用正则的情况下，纯字母没有任何结果，这是否正常？主程序和扩展都是最新正式版。

**Comment by Chaoses-Ib** [comment]
![image](https://user-images.githubusercontent.com/50246090/172658606-53bc7593-7f1f-4382-862d-2638be92ca8e.png)
![image](https://user-images.githubusercontent.com/50246090/172658522-d0e66bd2-2228-4b8a-b1cd-d1a6fd85310c.png)
![image](https://user-images.githubusercontent.com/50246090/172659929-2d7da459-8a0b-44c7-8fdf-f140fc6f5fe1.png)
![image](https://user-images.githubusercontent.com/50246090/172659970-c877ccc7-05a8-4055-8cbf-b4066a5663f1.png)

扩展版本 v0.6-alpha.2，在 Everything v1.5.0.1305 和 v1.4.1.1015 下均无法复现问题。

**Comment by StrollStars** [comment]
@Chaoses-Ib 谢谢多次耐心答复
