### ISSUE TITLE
V1.4.1.1018 (x64) 是不是只支持Edit模式

### ISSUE THREAD

**Issue by shuohao** [Chaoses-Ib/IbEverythingExt#59]
![image](https://user-images.githubusercontent.com/4637107/185373016-d2ec8167-e3dd-466c-999e-89efaffed24f.png)

我启动后就提示edit模式，不支持全拼

**Comment by Chaoses-Ib** [comment]
你用的扩展是什么版本？只有昨天发布的 [v0.6-alpha.4](https://github.com/Chaoses-Ib/IbEverythingExt/releases/tag/v0.6-alpha.4) 才支持 v1.4.1.1018。

**Comment by shuohao** [comment]
> 你用的扩展是什么版本？只有昨天发布的 [v0.6-alpha.4](https://github.com/Chaoses-Ib/IbEverythingExt/releases/tag/v0.6-alpha.4) 才支持 v1.4.1.1018。

IbEverythingExt v0.6-alpha.4   windows11报毒。。。
![image](https://user-images.githubusercontent.com/4637107/185525134-df4783da-2fa4-461c-af57-a09d4ada4ee5.png)
![image](https://user-images.githubusercontent.com/4637107/185525159-08f919a9-6077-4bc7-8e61-67901ae1f252.png)

**Comment by Chaoses-Ib** [comment]
报毒很正常，这本来就是用非正常方法修改的 Everything，加白名单就行了。如果你信不过的话可以自己编译，或者不用。

**Comment by shuohao** [comment]
> 报毒很正常，这本来就是用非正常方法修改的 Everything，加白名单就行了。如果你信不过的话可以自己编译，或者不用。

没有信不过，只是以前版本没有这个问题，就当是个优化建议如果能去掉报毒就好了。    另外用alpha.4可以正常用了 感谢

**Comment by Chaoses-Ib** [comment]
从提示里看似乎是更新检查器的问题，可能是把访问 GitHub 当成了下载恶意代码。这部分之后可能会跟 GUI 一起用 .NET 重写，如果到时候还误报的话我再给微软提交申诉吧。
