### ISSUE TITLE
指定路径搜索时，无法搜索扩展名 #bug

### ISSUE THREAD

**Issue by BINGHAOO** [Chaoses-Ib/IbEverythingExt#62]
例如：在YOU-GET文件夹下搜索所有得jpg文件："C:\YOU-GET\" .jpg，返回结果为0，删除扩展后可以正常搜索

**Comment by Chaoses-Ib** [comment]
![image](https://user-images.githubusercontent.com/50246090/193760817-a82b53f0-4daf-4e58-8b52-8bed7b1c1120.png)

Everything v1.5.0.1318 + 扩展 v0.6-alpha.5 下无法复现，你用的是什么版本？除了匹配路径还选了别的选项吗？

**Comment by BINGHAOO** [comment]
之前使用的V0.3版本，更新到V0.5版本以后问题不再复现，已解决，感谢您！
![image](https://user-images.githubusercontent.com/38246715/194570541-1eca2cfa-8842-4c10-b124-a0590e84c8c1.png)
