### ISSUE TITLE
求更新适配新版everything1021

### ISSUE THREAD

**Issue by hekeledeJudy** [Chaoses-Ib/IbEverythingExt#63]
求更新适配新版everything1021  感谢大佬~

**Comment by Chaoses-Ib** [comment]
经测试，[v0.6-alpha.5](https://github.com/Chaoses-Ib/IbEverythingExt/releases/tag/v0.6-alpha.5) 的特征码匹配可用于 v1.4.1.1021：

![image](https://user-images.githubusercontent.com/50246090/194313292-d667fcfc-0ae2-46cf-91b8-542b45cd299c.png)
