### ISSUE TITLE
Everything 1.4.1.1023版本更新了，老哥有空的话适配下，有劳了

### ISSUE THREAD

**Issue by Liceaction** [Chaoses-Ib/IbEverythingExt#72]
更新了Everything 1.4.1.1023版本，好像失效了

**Comment by Chaoses-Ib** [comment]
![image](https://github.com/Chaoses-Ib/IbEverythingExt/assets/50246090/e37961e1-e181-4d75-8bda-31dbd8940ed6)

我这边没法复现，拼音搜索和快速选择都正常。你们更新的是 x64 版本的吗？

**Comment by Liceaction** [comment]
> ![image](https://user-images.githubusercontent.com/50246090/239014238-e37961e1-e181-4d75-8bda-31dbd8940ed6.png)
> 
> 我这边没法复现，拼音搜索和快速选择都正常。你们用的扩展版本是 v0.6-alpha.5 吗？Everything 是 x64 版本的吗？

谢谢，可以支持的，是我没注意安装了X86
